#:kivy 2.0

WindowManager:
    IdleWindow:
    LoggedWindow:

<IdleWindow>:
    name: "idle"

    Button:
        text: "Login"
        on_release:
            app.root.current = "logged"
            root.manager.transition.direction = "up"

<LoggedWindow>:
    name: "logged"

    Button:
        text: "Go back"
        on_release:
            app.root.current = "idle"
            root.manager.transition.direction = "down"
