API_BASE_URL = "http://1c86ee0f38d8.ngrok.io"
user_1 = "alvaro@email.com"
user_2 = "arnold@email.com"
user_3 = "george@email.com"
user_4 = "jennifer@email.com"
user_5 = "tiger@email.com"
PASSWORD = "password"
